# travis ci(持续集成)配置文件
language: node_js # 测试语言
node_js: # 语言版本
  - "node"
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
